"""
Package the code + processed data needed to run training OR evaluation on
Colab (or any other CUDA machine) into a single zip for upload to Google Drive.

Phase 3a only needs the SOURCE split, so target countries are excluded by
default -- they roughly double the upload size and are not touched until
Phase 4.

Usage:
    # Phase 3a bundle (code + SOURCE split, for training)
    python scripts/make_colab_bundle.py

    # Phase 4 bundle: cross-country EVAL on GPU (target data + trained
    # weights + current experiment_log.csv, so Colab can resume-skip whatever
    # (model, dataset) pairs are already logged instead of redoing them --
    # source/ is deliberately NOT bundled by --include-target; only its small
    # test split is, as a safety net in case resume-skip doesn't trigger)
    python scripts/make_colab_bundle.py --include-target --include-weights faster_rcnn_source

Writes:
    dist/rdd_bundle.zip
"""

import argparse
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "dist"

# Code and config always travel with the data so the Colab run executes the
# same scripts that were developed and smoke-tested locally.
CODE_DIRS = ["src", "config", "scripts"]
CODE_FILES = ["requirements.txt", "README.md"]

# Excluded everywhere except --include-weights' explicit selections: caches,
# and stray checkpoints (weights are normally large and regenerated by
# training anyway -- --include-weights is the deliberate exception for an
# eval-only bundle that needs an ALREADY-TRAINED checkpoint).
EXCLUDE_SUFFIXES = {".pyc", ".pt", ".pth"}
EXCLUDE_DIR_NAMES = {"__pycache__", ".ipynb_checkpoints"}


def should_skip(path: Path) -> bool:
    if path.suffix.lower() in EXCLUDE_SUFFIXES:
        return True
    return any(part in EXCLUDE_DIR_NAMES for part in path.parts)


def add_tree(zf: zipfile.ZipFile, root: Path, counter: dict, label: str):
    if not root.exists():
        print(f"  [skip] {label}: {root} not found")
        return
    n = 0
    for path in root.rglob("*"):
        if path.is_file() and not should_skip(path):
            zf.write(path, path.relative_to(REPO_ROOT).as_posix())
            n += 1
    counter[label] = n
    print(f"  {label}: {n} files")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--include-target", action="store_true",
                    help="also bundle the zero-shot TARGET countries (needed from Phase 4 on)")
    ap.add_argument("--include-subset", action="store_true", default=True,
                    help="include the small smoke-test subset (cheap, useful for validating on Colab first)")
    ap.add_argument("--no-source", action="store_true",
                    help="skip the full SOURCE train/val/test split. Bundles only "
                         "data/processed/source/{images,labels}/test as a safety net for "
                         "cross_country_eval.py's in-domain reference row, in case its "
                         "resume-skip (matching experiment_log.csv row) doesn't trigger. "
                         "Use for an eval-only Phase 4 bundle -- training needs the full split.")
    ap.add_argument("--include-weights", nargs="+", default=[],
                    help="run directory name(s) under experiments/runs/ whose best.pt (and "
                         "last.pt if present) should be bundled -- e.g. faster_rcnn_source. "
                         "Needed for an EVAL bundle (Colab must load an already-trained "
                         "checkpoint); never needed for a training bundle.")
    ap.add_argument("--include-logs", action="store_true", default=True,
                    help="bundle experiments/results/*.csv (experiment_log.csv and any "
                         "cross_country_results.csv) so Colab-side runs can resume-skip "
                         "whatever is already logged instead of redoing it.")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / "rdd_bundle.zip"

    counter: dict[str, int] = {}
    print(f"Building {out_path}")

    # ZIP_DEFLATED on JPEGs gains little, but costs little too, and keeps the
    # code/text portions small.
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for d in CODE_DIRS:
            add_tree(zf, REPO_ROOT / d, counter, f"code/{d}")
        for f in CODE_FILES:
            p = REPO_ROOT / f
            if p.exists():
                zf.write(p, p.relative_to(REPO_ROOT).as_posix())

        if args.no_source:
            for split in ("test",):
                add_tree(zf, REPO_ROOT / "data" / "processed" / "source" / "images" / split,
                         counter, f"data/source/images/{split}")
                add_tree(zf, REPO_ROOT / "data" / "processed" / "source" / "labels" / split,
                         counter, f"data/source/labels/{split}")
        else:
            add_tree(zf, REPO_ROOT / "data" / "processed" / "source", counter, "data/source")
        if args.include_subset and not args.no_source:
            add_tree(zf, REPO_ROOT / "data" / "processed" / "source_subset",
                     counter, "data/source_subset")
        if args.include_target:
            add_tree(zf, REPO_ROOT / "data" / "processed" / "target", counter, "data/target")

        for run_name in args.include_weights:
            run_dir = REPO_ROOT / "experiments" / "runs" / run_name
            n = 0
            for weight_name in ("best.pt", "last.pt"):
                p = run_dir / weight_name
                if p.exists():
                    zf.write(p, p.relative_to(REPO_ROOT).as_posix())
                    n += 1
                # YOLO nests weights one level deeper.
                p2 = run_dir / "weights" / weight_name
                if p2.exists():
                    zf.write(p2, p2.relative_to(REPO_ROOT).as_posix())
                    n += 1
            counter[f"weights/{run_name}"] = n
            print(f"  weights/{run_name}: {n} files")
            if n == 0:
                print(f"    WARNING: no checkpoint found under {run_dir} -- Colab-side eval will fail to load it.")

        if args.include_logs:
            for f in ["experiments/results/experiment_log.csv",
                      "experiments/results/cross_country_results.csv"]:
                p = REPO_ROOT / f
                if p.exists():
                    zf.write(p, f)
                    print(f"  {f}: included")

        # Carry the provenance files so the Colab side can verify it received
        # the same data that was reported on locally.
        for f in ["data/DATA_REPORT.md", "data/split_report.json",
                  "data/verification_report.json"]:
            p = REPO_ROOT / f
            if p.exists():
                zf.write(p, f)

    size_gb = out_path.stat().st_size / 1e9
    print(f"\nWrote {out_path}  ({size_gb:.2f} GB, {sum(counter.values())} files)")
    print("\nNext: upload this zip to Google Drive, then run the matching Colab notebook.")


if __name__ == "__main__":
    main()
